### ISSUE TITLE
[Intellisense] type[][] not assignable to arrayref<type[][]>

### ISSUE THREAD

**Issue by CameronClay** [Talv/vscode-sc2-galaxy#3]
Code used to test

```cpp
typedef int[CS_TABIDX_COUNT][CS_INT_MAX] CSPlayerField;
typedef arrayref<CSPlayerField> CSPlayerField_T;

int[CS_TABIDX_COUNT][CS_INT_MAX] enabled;
void fn(CSPlayerField_T playerField) {}

fn(enabled);
```

Results in the following intellisense error: `Type 'integer[][]' is not assignable to type 'arrayref<integer[][]>'typecheck`
The code compiles with no issues.

**Comment by Talv** [comment]
Thanks for the report. Fixed in https://github.com/Talv/plaxtony/commit/d6ef07befe1cae4cc6da5f92f75967c13461fc40
