### ISSUE TITLE
[Bug]::[Intellisense] Improper struct properties validation

### ISSUE THREAD

**Issue by MadProbe** [Talv/vscode-sc2-galaxy#4]
The following code snippets should fail since structref<> and arrayref<> are disallowed in structs.
```
struct struct1 {
    structref<> p2;
};
```
```
struct struct1 {
    structref<struct1> p2;
};
```
```
struct struct1 {
    int i;
};
struct struct2 {
    structref<struct1> p1;
};
```
Also intellisense doesn't detect structures with circular references.

**Comment by Talv** [comment]
Thanks for the report. Fixed in https://github.com/Talv/plaxtony/commit/aaba69a8b0ec12cfbc436ce4ec052febc3ea626f
